- name: Deploy chatset-back
  hosts: webservers
  become: true
  vars:
    repo_url: https://github.com/IgorTikush/chatset-back.git
    app_dir: /root/chatset-back

  tasks:
    - name: Remove old application directory
      file:
        path: "{{ app_dir }}"
        state: absent

    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main

    - name: Install Yarn dependencies and build the app
      shell: |
        cd {{ app_dir }}
        yarn install
        yarn build
      args:
        chdir: "{{ app_dir }}"

    - name: Restart chatset service
      systemd:
        name: chatset
        state: restarted
